### ISSUE TITLE
abstract Shibboleth config into shibboleth.yml

### ISSUE THREAD

**Issue by jshslsky** [ucla-oarc-mobile/casa-on-rails#75]
This will allow us to override Shibboleth configuration properties without having to alter source code fragments or replace entire source code files as is currently done in Chef. 

In the new YAML file it should be possible to override both `config.oauth2` and `config.login_route`.

The configuration data structure is [here](https://github.com/ucla/casa-on-rails/blob/master/config/environments/development.rb#L39).

**Comment by jshslsky** [comment]
Example YAML.

```
oauth2:
  provider:
    shibboleth:
      enabled: true
      key: casa
      secret: asac
      properties:
        site: http://local-auth
        authorize_url: /oauth2/test-authorize
        token_url: /oauth2/access_token
      routes:
        get_user: /oauth2/user
      restrict_to:
        eduPersonPrinicipalName:
          - jselsky@ucla.edu
        eduPersonScopedAffiliation:
          - employee@ucla.edu

login_route:
  - session_oauth2_launch_url
  - shibboleth
```
